### ISSUE TITLE
De Wollok a Kotlin: mostrar cómo crear un objeto

### ISSUE THREAD

**Issue by faloi** [obj2-unahur/obj2-unahur.github.io#10]
A continuación del ejemplo de clases, mostrar uno con objetos. Pueden ser, por ejemplo, tipos de comida: mijo, alpiste, etc.

**Comment by faloi** [comment]
En [este apunte](https://www.wollok.org/documentacion/conceptos/#objetos-anonimos) se explica cómo es la sintaxis de Wollok.

**Comment by afska** [comment]
Agregado en https://github.com/obj2-unahur/obj2-unahur.github.io/commit/cd5aa8a7d40f9a965766a0c82f5157fe8e1d3b4f
