### ISSUE TITLE
Buscar textos que falten traducir

### ISSUE THREAD

**Issue by faloi** [obj2-unahur/obj2-unahur.github.io#2]
El template no está completamente localizado, y eso dificulta la traducción. Ya me encargué de una gran parte de los textos pero probablemente falten algunos más.

Habría que navegar un rato el sitio y buscar qué textos faltan.

**Comment by faloi** [comment]
En **mobile** dice Post arriba de todo. Cuando scrolleas cambia por el nombre del artículo.

![Screenshot_2021-03-23-18-48-45-018_com.brave.browser.jpg](https://user-images.githubusercontent.com/1585835/112223298-7970e180-8c08-11eb-9a01-ccdac00a3808.jpg)

**Comment by AngeliMatias** [comment]
**General - Pasan en Desktop y Mobile:**

- En la sección de comentarios en los articulos (por ahora solo está el de prueba) figura en inglés "Do not sell My Data" abajo de la caja de comentarios.
![WhatsApp Image 2021-03-23 at 21 16 49](https://user-images.githubusercontent.com/46464403/112238687-e80f6880-8c23-11eb-91c7-2ece87bdd1c9.jpeg)

- En la página "Acerca de" la nota respecto a como agregar contenido a esa sección está en inglés, es algo que falta completar nada más pero lo menciono por si acaso.
![WhatsApp Image 2021-03-23 at 21 17 02](https://user-images.githubusercontent.com/46464403/112238796-18ef9d80-8c24-11eb-9fc5-8274d5f5eddb.jpeg)

- En el feed.xml (Se accede clickeando el logo de más a la derecha en la barra de la izquierda) el subtítulo de la página figura en inglés
![WhatsApp Image 2021-03-23 at 21 17 49 (1)](https://user-images.githubusercontent.com/46464403/112238895-489ea580-8c24-11eb-9572-53e1a7e6fbbd.jpeg)

**Comment by AngeliMatias** [comment]
En Mobile:
Similar a lo encontrado por Fede, en Mobile figura Tag en lugar de Etiquetas y Category en lugar de Categorias, no pude comprobar si al scrollear se corrige porque el contenido de las páginas es muy corto.
![WhatsApp Image 2021-03-23 at 22 12 01](https://user-images.githubusercontent.com/46464403/112239280-f14d0500-8c24-11eb-9e9a-bd1c74ce9bbc.jpeg)
![WhatsApp Image 2021-03-23 at 22 12 01 (1)](https://user-images.githubusercontent.com/46464403/112239283-f27e3200-8c24-11eb-8bf3-5a0ff7d49280.jpeg)
