### ISSUE TITLE
Corregir las flechas de las categorías

### ISSUE THREAD

**Issue by AngeliMatias** [obj2-unahur/obj2-unahur.github.io#5]
Las categorías tienen unas fechas que al pasar el mouse por encima muestran un cartelito prohibiendo el clickeo. Se puede acceder a las categorías clickeando el título de todas maneras asi que las flechitas son innecesarias

![Captura de pantalla](https://user-images.githubusercontent.com/46464403/112732560-76803480-8f19-11eb-9230-90744eb39a1b.png)

**Comment by faloi** [comment]
Parece que las flechas sirven cuando tenés subcategorías:

![flechas](https://user-images.githubusercontent.com/1585835/113068263-5a3bfc00-9194-11eb-895f-5a4864fe3687.gif)

De todas formas, coincido en que confunden. Mejor las saco si no hay subcategoría.
